import './stores'
import './context'

import './core/index'
import './managers/index'
import './objects/index'
import './scenes/index'
import './sprites/index'
import './windows/index'
/*
import {
  JsExtensions,
  Utils,
  CacheEntry,
  CacheMap,
  ImageCache,
  RequestQueue,
  Point,
  Rectangle,
  Bitmap,
  Decrypter,
  Graphics,
  Input,
  TouchInput,
  Sprite,
  Tilemap,
  TilingSprite,
  ScreenSprite,
  ShaderTilemap,
  Window,
  WindowLayer,
  Weather,
  ToneFilter,
  ToneSprite,
  Stage,
  WebAudio,
  Html5Audio,
  JsonEx,
  ResourceHandler,
} from "./core/index"

import {
  DataManager,
  ConfigManager,
  StorageManager,
  ImageManager,
  AudioManager,
  SoundManager,
  TextManager,
  SceneManager,
  BattleManager,
  PluginManager
} from "./managers/index"

import {
  Game_Temp,
  Game_System,
  Game_Timer,
  Game_Message,
  Game_Switches,
  Game_Variables,
  Game_SelfSwitches,
  Game_Screen,
  Game_Picture,
  Game_Item,
  Game_Action,
  Game_ActionResult,
  Game_BattlerBase,
  Game_Battler,
  Game_Actor,
  Game_Enemy,
  Game_Actors,
  Game_Unit,
  Game_Party,
  Game_Troop,
  Game_Map,
  Game_CommonEvent,
  Game_CharacterBase,
  Game_Character,
  Game_Player,
  Game_Follower,
  Game_Followers,
  Game_Vehicle,
  Game_Event,
  Game_Interpreter,
} from "./objects/index"

import {
  Scene_Base,
  Scene_Boot,
  Scene_Title,
  Scene_Map,
  Scene_MenuBase,
  Scene_Menu,
  Scene_ItemBase,
  Scene_Item,
  Scene_Skill,
  Scene_Equip,
  Scene_Status,
  Scene_Options,
  Scene_File,
  Scene_Save,
  Scene_Load,
  Scene_GameEnd,
  Scene_Shop,
  Scene_Name,
  Scene_Debug,
  Scene_Battle,
  Scene_Gameover,
} from "./scenes/index"

import {
  Sprite_Base,
  Sprite_Button,
  Sprite_Character,
  Sprite_Battler,
  Sprite_Actor,
  Sprite_Enemy,
  Sprite_Animation,
  Sprite_Damage,
  Sprite_StateIcon,
  Sprite_StateOverlay,
  Sprite_Weapon,
  Sprite_Balloon,
  Sprite_Picture,
  Sprite_Timer,
  Sprite_Destination,
  Spriteset_Base,
  Spriteset_Map,
  Spriteset_Battle,
} from "./sprites/index"

import {
  Window_Base,
  Window_Selectable,
  Window_Command,
  Window_HorzCommand,
  Window_Help,
  Window_Gold,
  Window_MenuCommand,
  Window_MenuStatus,
  Window_MenuActor,
  Window_ItemCategory,
  Window_ItemList,
  Window_SkillType,
  Window_SkillStatus,
  Window_SkillList,
  Window_EquipStatus,
  Window_EquipCommand,
  Window_EquipSlot,
  Window_EquipItem,
  Window_Status,
  Window_Options,
  Window_SavefileList,
  Window_ShopCommand,
  Window_ShopBuy,
  Window_ShopSell,
  Window_ShopNumber,
  Window_ShopStatus,
  Window_NameEdit,
  Window_NameInput,
  Window_ChoiceList,
  Window_NumberInput,
  Window_EventItem,
  Window_Message,
  Window_ScrollText,
  Window_MapName,
  Window_BattleLog,
  Window_PartyCommand,
  Window_ActorCommand,
  Window_BattleStatus,
  Window_BattleActor,
  Window_BattleEnemy,
  Window_BattleSkill,
  Window_BattleItem,
  Window_TitleCommand,
  Window_GameEnd,
  Window_DebugRange,
  Window_DebugEdit,
} from "./windows/index"
 */

import './make_global'